//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from json.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="jsonParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IjsonListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="jsonParser.json"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJson([NotNull] jsonParser.JsonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="jsonParser.json"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJson([NotNull] jsonParser.JsonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="jsonParser.obj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObj([NotNull] jsonParser.ObjContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="jsonParser.obj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObj([NotNull] jsonParser.ObjContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="jsonParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPair([NotNull] jsonParser.PairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="jsonParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPair([NotNull] jsonParser.PairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="jsonParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray([NotNull] jsonParser.ArrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="jsonParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray([NotNull] jsonParser.ArrayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="jsonParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] jsonParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="jsonParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] jsonParser.ValueContext context);
}
