name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- main
- master
- dotliquid
- refs/heads/dotliquid
pr:
- dotliquid
- main
- xoriant/*

variables:
  solution: '**/*.sln'
  unitTestProjects: "**/*UnitTests/*.csproj"
  publishProject: "**/*Tool/*.csproj"
  functionalTests: "**/*FunctionalTests/*.csproj"
  buildConfiguration: 'Release'
  major: 4
  minor: 2
  patch: 0
  buildnum: $[counter(format('{0}.{1}.{2}',variables['major'],variables['minor'], variables['patch']), 1)]
  version: $(major).$(minor).$(patch).$(buildnum)

stages:

- stage: FunctionalTests
  jobs:
  - job: Windows_Functional_Test
    pool: CompassMacHosted
    steps:
    
    - script: |
        docker pull registry:2
        docker tag registry:2 dockerhub.io/wusongrui/registry:2.7.1.sowu
      displayName: start registry
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhubsowu'
        repository: 'dockerhub.io/wusongrui/registry'
        command: 'push'
        tags: '2.7.1.sowu'
    
