name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- main
- master
- dotliquid
- refs/heads/dotliquid
pr:
- dotliquid
- main
- xoriant/*

variables:
  solution: '**/*.sln'
  unitTestProjects: "**/*UnitTests/*.csproj"
  publishProject: "**/*Tool/*.csproj"
  functionalTests: "**/*FunctionalTests/*.csproj"
  buildConfiguration: 'Release'
  major: 4
  minor: 2
  patch: 0
  buildnum: $[counter(format('{0}.{1}.{2}',variables['major'],variables['minor'], variables['patch']), 1)]
  version: $(major).$(minor).$(patch).$(buildnum)

stages:

- stage: FunctionalTests
  jobs:
  - job: Windows_Functional_Test
    pool:
        vmImage: 'windows-latest'
    steps:
    - script: |
        docker pull registry:2
        docker login -u {user} -p {password}
        docker tag registry:2 docker.io/wusongrui/registry:sowu
        docker push docker.io/wusongrui/registry:sowu
      displayName: start registry
