{{- if .Values.fhir.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restricted-psp-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames:
      - restricted-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restricted-psp-{{ .Chart.Name }}-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: restricted-psp-{{ .Chart.Name }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  # Authorize all service accounts in a namespace:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:serviceaccounts
{{- end }}
