name: Docker Image CI

on: 
  push:
    branches:
      - '*/*/*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
      
    - name: Set output
      id: extractbranchname
      run: echo ::set-output name=short_ref::${GITHUB_REF##*/}
      
    - uses: azure/docker-login@v1
      with:
        login-server: healthplatformregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t healthplatformregistry.azurecr.io/fhirconverter:branch-${{ steps.extractbranchname.outputs.short_ref }}
        docker push healthplatformregistry.azurecr.io/fhirconverter:branch-${{ steps.extractbranchname.outputs.short_ref }}
