name: Docker

on:
  push:
    # Publish `handlebars` as Docker `dev` image.
    branches:
      - handlebars
      - handlebars-stable

env:
  IMAGE_NAME: fhir-converter

jobs:
  push_to_registry:
    name: Publish Docker image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        registry:
          [
            "globalkaikuacr.azurecr.io",
            "tstglobalkaikuacr.azurecr.io",
            "eu.gcr.io/stevedore-production-42a0d764",
          ]
        include:
          - registry: globalkaikuacr.azurecr.io
            username: PROD_ACR_PUSH_USERNAME
            password: PROD_ACR_PUSH_PASSWORD
          - registry: tstglobalkaikuacr.azurecr.io
            username: TST_ACR_PUSH_USERNAME
            password: TST_ACR_PUSH_PASSWORD
          - registry: eu.gcr.io/stevedore-production-42a0d764
            username: GCR_USERNAME
            password: GCR_JSON_KEY
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Check out the docker-action repository
        uses: actions/checkout@v3
        with:
          repository: netMedi/docker-action
          token: ${{ secrets.GIT_ACTION_NETMEDI_INTEGRATION_PAT }}
          path: docker-action

      - name: Build & Push Docker image
        if: ${{ github.ref == 'refs/heads/handlebars' }}
        with:
          registry: ${{ matrix.registry }}
          image: ${{ env.IMAGE_NAME }}
          tag: dev
          username: ${{ secrets[matrix.username] }}
          password: ${{ secrets[matrix.password] }}
          trivy_exit_code: "0"
          trivy_format: "table"
          trivy_vuln_type: "os,library"
          trivy_severity: "CRITICAL,HIGH"
          trivy_ignore_unfixed: true
        uses: ./docker-action

      - name: Build & Push Docker image
        if: ${{ github.ref == 'refs/heads/handlebars-stable' }}
        with:
          registry: ${{ matrix.registry }}
          image: ${{ env.IMAGE_NAME }}
          tag: latest
          username: ${{ secrets[matrix.username] }}
          password: ${{ secrets[matrix.password] }}
          trivy_exit_code: "0"
          trivy_format: "table"
          trivy_vuln_type: "os,library"
          trivy_severity: "CRITICAL,HIGH"
          trivy_ignore_unfixed: true
        uses: ./docker-action
