name: Docker

on:
  push:
    # Publish `handlebars` as Docker `dev` image.
    branches:
      - handlebars
      - handlebars-stable
      - KAIKU-10645-docker-update


env:
  IMAGE_NAME: fhir-converter

jobs:
  docker-acr-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        registry: ["globalkaikuacr", "tstglobalkaikuacr"]
        include:
          - registry: "globalkaikuacr"
            acr_secret_username: "PROD_ACR_PUSH_USERNAME"
            acr_secret_password: "PROD_ACR_PUSH_PASSWORD"
          - registry: "tstglobalkaikuacr"
            acr_secret_username: "TST_ACR_PUSH_USERNAME"
            acr_secret_password: "TST_ACR_PUSH_PASSWORD"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # Connect to Azure Container Registry (ACR)
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ matrix.registry }}.azurecr.io
          username: ${{ secrets[matrix.acr_secret_username] }}
          password: ${{ secrets[matrix.acr_secret_password] }}
      - name: Build and push
        if: ${{ github.ref == 'refs/heads/KAIKU-10645-docker-update' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ matrix.registry }}.azurecr.io/${{ env.IMAGE_NAME }}:dev
      - name: Build and push
        if: ${{ github.ref == 'refs/heads/handlebars-stable' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ matrix.registry }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

  docker-gcp-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Connect to GCP container registry
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      - name: Build and push
        if: ${{ github.ref == 'refs/heads/KAIKU-10645-docker-update' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: eu.gcr.io/stevedore-production-42a0d764/${{ env.IMAGE_NAME }}:dev
      - name: Build and push
        if: ${{ github.ref == 'refs/heads/handlebars-stable' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: eu.gcr.io/stevedore-production-42a0d764/${{ env.IMAGE_NAME }}:latest
